Improve model backup handling. Delete existing model just before saving.

diff --git a/.github/workflows/train-pulls.yml b/.github/workflows/train-pulls.yml
--- a/.github/workflows/train-pulls.yml
+++ b/.github/workflows/train-pulls.yml
@@ -19,6 +19,7 @@ env:
   DATA_CACHE_KEY: github-ml-labeler/pulls/data${{ inputs.data_cache_key && format('/{0}', inputs.data_cache_key) }}
   MODEL_PATH: labeler-cache/pull-model.zip
   MODEL_CACHE_KEY: github-ml-labeler/pulls/model/${{ inputs.model_cache_key }}
+  BACKUP_CACHE_KEY: github-ml-labeler/pulls/model/${{ inputs.model_cache_key }}/backup
   GH_TOKEN: ${{ github.token }}
 
 jobs:
@@ -52,22 +53,35 @@ jobs:
           key: ${{ env.MODEL_CACHE_KEY }}
           fail-on-cache-miss: false
 
+      - name: "Check for existing backup cache entry"
+        id: check-backup
+        if: ${{ steps.check-cache.outputs.cache-hit == 'true' }}
+        uses: actions/cache/restore@v4
+        with:
+          path: ${{ env.MODEL_PATH }}
+          key: ${{ env.BACKUP_CACHE_KEY }}
+          lookup-only: true
+          fail-on-cache-miss: false
+
+      - name: "Abort if backup cache entry already exists"
+        if: ${{ steps.check-backup.outputs.cache-hit == 'true' }}
+        run: |
+            echo "Cannot save backup of existing model. Backup cache key already exists."
+            echo "Key: ${{ env.BACKUP_CACHE_KEY }}"
+
+            exit 1
+
       - name: "Cache backup of existing model"
         if: ${{ steps.check-cache.outputs.cache-hit == 'true' }}
         id: backup-model
         uses: actions/cache/save@v4
         with:
           path: ${{ env.MODEL_PATH }}
-          key: ${{ env.MODEL_CACHE_KEY }}/backup
+          key: ${{ env.BACKUP_CACHE_KEY }}
 
-      - name: "Delete existing model cache entry and local copy"
+      - name: "Delete restored model"
         if: ${{ steps.check-cache.outputs.cache-hit == 'true' }}
         run: |
-            gh api --method DELETE \
-              -H "Accept: application/vnd.github+json" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              /repos/${{ github.repository }}/actions/caches?key=${{ env.MODEL_CACHE_KEY }}
-
             rm ${{ env.MODEL_PATH }}
 
       - name: "Run Trainer"
@@ -75,6 +89,14 @@ jobs:
           dotnet run -c Release --project ./src/Trainer --  \
             ${{ format('--pull-data "{0}"', env.DATA_PATH) }} \
             ${{ format('--pull-model "{0}"', env.MODEL_PATH) }}
+
+      - name: "Delete existing model cache entry"
+        if: ${{ steps.check-cache.outputs.cache-hit == 'true' }}
+        run: |
+            gh api --method DELETE \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              /repos/${{ github.repository }}/actions/caches?key=${{ env.MODEL_CACHE_KEY }}
 
       - name: "Save model to cache"
         uses: actions/cache/save@v4
